In [ ]:
#question1: create a numpy array starting from 2 to till 50 with stepsize of 3.

import numpy as np
ar=np.arange(2,50,3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [ ]:
#question2:
import numpy as nm
list1,list2=[],[]
print("list items")
for i in range(5):
    t=int(input())
    list1.append(t)
print("list items")
for i in range(5):
    t=int(input())
    list2.append(t)
arr=nm.array([list1,list2])
print(arr)
print()
arr=arr.reshape(1,6)
arr=nm.sort(arr)
arr=arr.reshape(2,5)
print(arr)


In [ ]:
#question3:
arr = np.array([[1,2,3],[1,3,5],[1,3,4]])
print(arr.ndim)
print(arr.size)



2
9


In [ ]:
#question 4:
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)


1
2


In [ ]:
#question 5:
import numpy as np
a = np.array([[5, 2], 
              [7, 4]]) 
  
b = np.array([[8, 6], 
              [3, 8]]) 
print("Vertical stacking:\n", np.vstack((a, b))) 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[5 2]
 [7 4]
 [8 6]
 [3 8]]

Horizontal stacking:
 [[5 2 8 6]
 [7 4 3 8]]


In [ ]:
#question 6:
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3]))
